# Generated by Django 2.2.1 on 2019-07-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title', max_length=255)),
                ('slug', models.SlugField(help_text='It will auto-complete automically!', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Enter your post')),
                ('Address', models.CharField(help_text='enter the present address', max_length=255)),
                ('Published_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Author')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Categories')),
            ],
        ),
    ]
