# Generated by Django 2.2.1 on 2019-07-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190709_0716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacted',
        ),
    ]
