# Generated by Django 2.2.1 on 2019-07-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_post_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
    ]
