# Generated by Django 2.2.1 on 2019-07-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.IntegerField(choices=[(0, 'blogs'), (1, 'Technical-writings')], default=0, help_text='select category'),
        ),
    ]
