# Generated by Django 2.2.1 on 2019-07-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20190709_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(help_text='select category', on_delete=django.db.models.deletion.CASCADE, to='blogs.Categories'),
        ),
    ]
