# Generated by Django 2.2.1 on 2019-07-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_auto_20190709_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='enter feature image of post', upload_to='images/'),
        ),
    ]
